# Generated by Django 6.1 on 2026-08-11 17:51

import crudkit.fields
import crudkit.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Squashed initial migration for the packaged crudkit app.

    ``replaces`` covers the app's full pre-extraction history from the
    fenerum-crm monolith. Databases migrated to the end of that history
    record this migration as applied without running any SQL; fresh
    installs run it as a normal initial migration."""

    initial = True

    replaces = [
        ("crudkit", "0001_initial"),
        ("crudkit", "0002_changelog_deleted_changelog_merged_into_and_more"),
        ("crudkit", "0003_alter_changelog_options_alter_layout_options_and_more"),
        ("crudkit", "0004_alter_changelog_options_and_more"),
        ("crudkit", "0005_add_exchange_rate"),
        ("crudkit", "0006_alter_exchangerate_currency_worklog"),
        ("crudkit", "0007_alter_worklog_unique_together"),
        ("crudkit", "0008_task"),
        ("crudkit", "0009_alter_task_options_and_more"),
        ("crudkit", "0010_alter_task_options_alter_feeditem_pinned"),
        ("crudkit", "0011_alter_view_layout"),
        ("crudkit", "0012_snippet"),
        ("crudkit", "0013_delete_task"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Layout",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("model", crudkit.fields.ModelField(max_length=3)),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        encoder=crudkit.models.PrettyJSONEncoder,
                        help_text="Format: [field1, field2, ...] OR left/right: [ [field1, field2, ...], [field3, field4, ...] ]",
                        null=True,
                    ),
                ),
                (
                    "inlines",
                    models.JSONField(
                        blank=True,
                        encoder=crudkit.models.PrettyJSONEncoder,
                        help_text="Format: [ [Model, [field1, field2, field...] ]",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.layout",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "body",
                    crudkit.models.WYSIWYGEditorField(
                        help_text="The snippet content to insert"
                    ),
                ),
                (
                    "model_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of model TYPE_IDs this snippet is available for, e.g. ["CAS", "OPP"]. Empty means available everywhere.',
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.snippet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="View",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("model", crudkit.fields.ModelField(max_length=3)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("list", "List"),
                            ("kanban", "Kanban"),
                            ("gallery", "Gallery"),
                            ("swimlane", "Swimlane"),
                            ("conversation", "Conversation"),
                            ("quadrant", "Quadrant"),
                        ],
                        default="list",
                        max_length=128,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("default", models.BooleanField(blank=True, default=False)),
                ("public", models.BooleanField(blank=True, default=True)),
                ("show_in_menu", models.BooleanField(blank=True, default=True)),
                (
                    "show_badge_in_menu",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="This will make every page in the CRM load slower, please use with caution",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        encoder=crudkit.models.PrettyJSONEncoder,
                        help_text="Format: [field1, field2, field...]",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        encoder=crudkit.models.PrettyJSONEncoder,
                        help_text="Format: [[field, comparator, value], [field, comparator, value], ...]",
                        null=True,
                    ),
                ),
                (
                    "order_by",
                    models.CharField(
                        blank=True,
                        help_text="Format: field or -field - you can optionally add multiple with a comma between and not space",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("group_by", models.CharField(blank=True, max_length=128, null=True)),
                ("pivot_by", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "aggregate_by",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "aggregate_type",
                    models.CharField(
                        blank=True,
                        choices=[("sum", "Sum"), ("len", "Count")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.view",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                (
                    "related_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(
                        editable=False, null=True
                    ),
                ),
                (
                    "field_changes",
                    models.JSONField(
                        blank=True,
                        encoder=crudkit.models.PrettyJSONEncoder,
                        help_text='Format: {"field": ["old_value", "new_value"], "field2": ["old_value", "new_value"], ...}',
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.changelog",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="crudkit_cha_updated_95d09e_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                (
                    "currency",
                    crudkit.fields.CurrencyField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("DKK", "Danish Krone"),
                            ("GBP", "British Pound"),
                            ("SEK", "Swedish Krona"),
                            ("NOK", "Norwegian Krone"),
                        ],
                        default="EUR",
                        help_text="The target currency. Base currency is EUR.",
                        max_length=3,
                    ),
                ),
                ("from_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "to_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for rates that apply indefinitely",
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Exchange rate from EUR to target currency (1 EUR = X target currency)",
                        max_digits=16,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.exchangerate",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-from_date", "currency"],
                "indexes": [
                    models.Index(
                        fields=["currency", "from_date", "to_date"],
                        name="crudkit_exc_currenc_d4a07d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalObject",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("system_name", models.CharField(max_length=128)),
                ("system_id", models.CharField(max_length=128)),
                (
                    "related_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(
                        editable=False, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.externalobject",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("system_name", "system_id", "related_content_type")
                },
            },
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                (
                    "parent_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(editable=False),
                ),
                (
                    "related_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(
                        editable=False, null=True
                    ),
                ),
                ("body", crudkit.models.WYSIWYGEditorField(blank=True, null=True)),
                ("pinned", models.BooleanField(blank=True, default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.feeditem",
                    ),
                ),
                (
                    "parent_content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="parent_content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_content_type",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent_content_type", "parent_object_id"],
                        name="crudkit_fee_parent__06fb24_idx",
                    ),
                    models.Index(
                        fields=["related_content_type", "related_object_id"],
                        name="crudkit_fee_related_89a39d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                (
                    "related_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(editable=False),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When time tracking ended. Null means it's still active.",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about the time spent", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.worklog",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Log",
                "verbose_name_plural": "Work Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "end_at"],
                        name="crudkit_wor_created_0dbcaa_idx",
                    ),
                    models.Index(
                        fields=["related_content_type", "related_object_id"],
                        name="crudkit_wor_related_0c431f_idx",
                    ),
                ],
                "unique_together": {("created_by", "end_at")},
            },
        ),
    ]
