# Generated by Django 5.1.15 on 2026-08-24 11:38

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, F


def close_duplicate_active_worklogs(apps, schema_editor):
    worklog = apps.get_model("crudkit", "WorkLog")
    duplicate_users = (
        worklog.objects.filter(end_at__isnull=True)
        .values("created_by_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for row in duplicate_users:
        active = worklog.objects.filter(created_by_id=row["created_by_id"], end_at__isnull=True).order_by(
            "-created_at", "-pk"
        )
        keep_id = active.values_list("pk", flat=True).first()
        active.exclude(pk=keep_id).update(end_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crudkit", "0002_workspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="worklog",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("to_date__isnull", True),
                    ("to_date__gte", models.F("from_date")),
                    _connector="OR",
                ),
                name="crudkit_exchange_rate_dates_ordered",
            ),
        ),
        migrations.RunPython(close_duplicate_active_worklogs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="worklog",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_at__isnull", True)),
                fields=("created_by",),
                name="crudkit_one_active_worklog_per_user",
            ),
        ),
    ]
