# Generated by Django 5.1.15 on 2026-09-28 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crudkit", "0003_enforce_data_invariants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="changelog",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("restore", "Restore"),
                    ("action", "Action"),
                    ("merge", "Merge"),
                    ("revert", "Revert"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
        # The indexes (db_index here, AddIndex below) are built by 0006, concurrently
        # on PostgreSQL: building them here would block every write to the change
        # log (i.e. every write) while a large table is indexed.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name="changelog",
                    name="change_set",
                    field=models.UUIDField(blank=True, editable=False, null=True),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="changelog",
                    name="change_set",
                    field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="changelog",
            name="client",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="changelog",
            name="label",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name="changelog",
                    name="revert_of",
                    field=models.UUIDField(blank=True, editable=False, null=True),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="changelog",
                    name="revert_of",
                    field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="changelog",
            name="source",
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="changelog",
                    index=models.Index(
                        fields=["related_content_type", "related_object_id"],
                        name="crudkit_cha_related_df5fbc_idx",
                    ),
                ),
            ],
        ),
    ]
