# Generated by Django 5.1.15 on 2026-09-28 14:31

import crudkit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudkit", "0004_changelog_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIContext",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Markdown. Shown to the assistant and AI fields as written.",
                    ),
                ),
                (
                    "model_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of model TYPE_IDs this context applies to, e.g. ["CAS", "OPP"]. Empty means everywhere.',
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Lower comes first."),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit.aicontext",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI context",
                "verbose_name_plural": "AI context",
                "ordering": ["order", "name"],
            },
        ),
    ]
