# Generated by Django 5.1.15 on 2026-10-09 08:31

import crudkit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudkit", "0006_changelog_audit_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="view",
            name="badge_filters",
            field=models.JSONField(
                blank=True,
                encoder=crudkit.models.PrettyJSONEncoder,
                help_text="Extra filters applied on top of filters when counting the menu badge, e.g. only unread. Format: same as filters",
                null=True,
            ),
        ),
    ]
