// Map design-system icon names to lucide-react component names. App code can
// keep its design-kit naming (or pass an Ionicons-style name like
// `home-outline`) and we resolve to the right lucide icon.

import {
  Activity, AlertCircle, AlertTriangle, ArrowDown, ArrowDownUp,
  ArrowLeft, ArrowRight, ArrowRightCircle, ArrowUp, AtSign, BarChart, BarChart2,
  Bell, Bold, Briefcase, Building, Building2, Calendar,
  Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsUpDown, Circle,
  Clock, Columns, Copy, CornerUpLeft, CreditCard, DollarSign, Download, Edit,
  Edit3, ExternalLink, Eye, EyeOff, File, FileText, Filter,
  Globe, GripVertical, Hash, HelpCircle, Home, Inbox, Info, Italic,
  Kanban, Layers, LayoutGrid, Link as LinkIcon, List, Lock, LogIn, LogOut, Mail,
  Menu, MessageCircle, MessageSquare, MessagesSquare, Minus, Moon, MoreHorizontal, MoreVertical,
  PanelLeft, Paperclip, Pause, Phone, PhoneIncoming, PhoneOutgoing,
  PieChart, Play, Plus, PlusCircle, RefreshCcw, RefreshCw, Search, Send, Settings,
  Sparkles, Square, Star, StickyNote, Sun, Tag, Tags, Trash, Trash2,
  Unlock, Upload, User, UserPlus, Users, X,
  XCircle, Zap,
} from 'lucide-react';

// First, normalise legacy Ionicons-style names to a canonical lucide kebab name.
const ALIAS = {
  'home-outline': 'home',
  'search-outline': 'search',
  'person-outline': 'user',
  'people-outline': 'users',
  'chevron-forward': 'chevron-right',
  'chevron-back': 'chevron-left',
  'add': 'plus',
  'remove': 'minus',
  'close': 'x',
  'close-circle': 'x',
  'close-circle-outline': 'x-circle',
  'checkmark': 'check',
  'checkmark-circle-outline': 'check-circle',
  'alert-circle-outline': 'alert-circle',
  'document-outline': 'file',
  'document-text-outline': 'file-text',
  'information-circle-outline': 'info',
  'help-circle-outline': 'help-circle',
  'lock-closed-outline': 'lock',
  'lock-open-outline': 'unlock',
  'log-out-outline': 'log-out',
  'log-in-outline': 'log-in',
  'notifications-outline': 'bell',
  'settings-outline': 'settings',
  'layers-outline': 'layers',
  'mail-outline': 'mail',
  'mail-unread-outline': 'inbox',
  'chatbubble-outline': 'message-square',
  'chatbubble-ellipses-outline': 'message-circle',
  'call-outline': 'phone',
  'calendar-outline': 'calendar',
  'time-outline': 'clock',
  'business-outline': 'building',
  'pricetag-outline': 'tag',
  'pricetags-outline': 'tags',
  'filter-outline': 'filter',
  'flash-outline': 'zap',
  'pulse-outline': 'activity',
  'grid-outline': 'layout-grid',
  'apps-outline': 'columns',
  'bar-chart-outline': 'bar-chart',
  'stats-chart-outline': 'bar-chart-2',
  'pie-chart-outline': 'pie-chart',
  'warning-outline': 'alert-triangle',
  'sunny-outline': 'sun',
  'moon-outline': 'moon',
  'globe-outline': 'globe',
  'send-outline': 'send',
  'download-outline': 'download',
  'cloud-upload-outline': 'upload',
  'refresh': 'refresh-cw',
  'create-outline': 'edit',
  'pencil-outline': 'edit-3',
  'trash-outline': 'trash-2',
  'copy-outline': 'copy',
  'link-outline': 'link',
  'star-outline': 'star',
  'eye-outline': 'eye',
  'eye-off-outline': 'eye-off',
  'open-outline': 'external-link',
  'add-circle-outline': 'plus-circle',
  'arrow-forward': 'arrow-right',
  'arrow-back': 'arrow-left',
  'arrow-forward-circle-outline': 'arrow-right-circle',
  'swap-vertical': 'arrow-down-up',
  'swap-vertical-outline': 'chevrons-up-down',
  'ellipsis-horizontal': 'more-horizontal',
  'ellipsis-vertical': 'more-vertical',
  'menu-outline': 'menu',
  'square-outline': 'square',
  'ellipse-outline': 'circle',
  'at-outline': 'at-sign',
  'text-outline': 'bold',
  'cash-outline': 'dollar-sign',
  'card-outline': 'credit-card',
  'briefcase-outline': 'briefcase',
  'person-add-outline': 'user-plus',
  'attach-outline': 'paperclip',
};

const ICONS = {
  'panel-left': PanelLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevrons-up-down': ChevronsUpDown,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'x': X,
  'check': Check,
  'plus': Plus,
  'minus': Minus,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-down-up': ArrowDownUp,
  'arrow-right-circle': ArrowRightCircle,
  'plus-circle': PlusCircle,
  'external-link': ExternalLink,
  'edit': Edit,
  'edit-3': Edit3,
  'trash': Trash,
  'trash-2': Trash2,
  'copy': Copy,
  'link': LinkIcon,
  'star': Star,
  'settings': Settings,
  'log-out': LogOut,
  'log-in': LogIn,
  'eye': Eye,
  'eye-off': EyeOff,
  'lock': Lock,
  'unlock': Unlock,
  'inbox': Inbox,
  'mail': Mail,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  'message-circle': MessageCircle,
  'phone': Phone,
  'phone-incoming': PhoneIncoming,
  'phone-outgoing': PhoneOutgoing,
  'calendar': Calendar,
  'clock': Clock,
  'users': Users,
  'user': User,
  'user-plus': UserPlus,
  'building': Building,
  'building-2': Building2,
  'home': Home,
  'file': File,
  'file-text': FileText,
  'sticky-note': StickyNote,
  'paperclip': Paperclip,
  'tag': Tag,
  'tags': Tags,
  'filter': Filter,
  'search': Search,
  'bell': Bell,
  'zap': Zap,
  'activity': Activity,
  'list': List,
  'kanban': Kanban,
  'grid': LayoutGrid,
  'layout-grid': LayoutGrid,
  'columns': Columns,
  'bar-chart': BarChart,
  'bar-chart-2': BarChart2,
  'pie-chart': PieChart,
  'help-circle': HelpCircle,
  'info': Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'sun': Sun,
  'moon': Moon,
  'globe': Globe,
  'send': Send,
  'download': Download,
  'upload': Upload,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  'play': Play,
  'pause': Pause,
  'square': Square,
  'circle': Circle,
  'at-sign': AtSign,
  'hash': Hash,
  'bold': Bold,
  'italic': Italic,
  'menu': Menu,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'briefcase': Briefcase,
  'sparkles': Sparkles,
  'layers': Layers,
  'grip-vertical': GripVertical,
  'corner-up-left': CornerUpLeft,
};

export function mapIcon(name) {
  if (!name) return HelpCircle;
  const canonical = ALIAS[name] || name;
  return ICONS[canonical] || HelpCircle;
}
