# Generated by Django 5.1.7 on 2026-05-18 18:08

import crudkit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantProposal",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                (
                    "target_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(editable=False),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("action", "Run action"),
                            ("patch", "Update fields"),
                            ("note", "Add note"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable summary for the Confirm card.",
                        max_length=255,
                    ),
                ),
                ("reasoning", models.TextField(blank=True, default="")),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Action name + args, patch fields, or note body.",
                    ),
                ),
                (
                    "outcome",
                    models.JSONField(
                        blank=True,
                        help_text="What the action returned or error info.",
                        null=True,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_proposal_confirmed_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit_assistant.assistantproposal",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_key", "status"],
                        name="crudkit_ass_session_53cfdd_idx",
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"],
                        name="crudkit_ass_target__5c8791_idx",
                    ),
                ],
            },
        ),
    ]
