# Generated by Django 5.1.15 on 2026-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudkit_assistant", "0002_assistantconversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantproposal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("action", "Run action"),
                    ("patch", "Update fields"),
                    ("note", "Add note"),
                    ("revert", "Revert change"),
                ],
                max_length=16,
            ),
        ),
    ]
