# Generated by Django 5.1.15 on 2026-09-28 15:33

import crudkit.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crudkit_assistant", "0003_proposal_revert"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantproposal",
            name="client",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=255
            ),
        ),
        migrations.AddField(
            model_name="assistantproposal",
            name="source",
            field=models.CharField(
                choices=[
                    ("assistant", "Assistant"),
                    ("mcp", "MCP"),
                    ("agent", "Agent"),
                ],
                default="assistant",
                editable=False,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="assistantproposal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("action", "Run action"),
                    ("patch", "Update fields"),
                    ("note", "Add note"),
                    ("revert", "Revert change"),
                    ("create", "Create record"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="assistantproposal",
            name="payload",
            field=models.JSONField(
                default=dict,
                help_text="Action name + args, patch or create fields, or note body.",
            ),
        ),
        migrations.AlterField(
            model_name="assistantproposal",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="assistantproposal",
            name="target_content_type",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="assistantproposal",
            name="target_object_id",
            field=crudkit.models.CrudKitPositiveIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
