# Generated by Django 5.1.15 on 2026-09-28 17:37

import crudkit.fields
import crudkit.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("crudkit", "0005_aicontext"),
        ("crudkit_assistant", "0004_proposal_sources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "instructions",
                    models.TextField(
                        help_text="What the agent should do with each record, in plain language."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("record_created", "Record created"),
                            ("record_changed", "Record changed"),
                            ("schedule", "Schedule"),
                            ("manual", "Manual"),
                        ],
                        default="record_changed",
                        max_length=16,
                    ),
                ),
                (
                    "model_type",
                    crudkit.fields.ModelField(
                        help_text="The record type (TYPE_ID) the agent works on.",
                        max_length=3,
                    ),
                ),
                (
                    "watch_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='For "Record changed": run only when one of these fields changed. Empty means any field.',
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "last_scheduled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("propose", "Propose changes"),
                            ("auto", "Apply changes"),
                        ],
                        default="propose",
                        max_length=16,
                    ),
                ),
                ("max_records_per_run", models.PositiveIntegerField(default=25)),
                ("max_runs_per_day", models.PositiveIntegerField(default=200)),
                (
                    "consecutive_failures",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit_assistant.agent",
                    ),
                ),
                (
                    "run_as",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user whose permissions the agent has. Defaults to its creator.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only records in this saved view are worked on.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="crudkit.view",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    crudkit.models.CrudKitIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False, editable=False)),
                (
                    "target_object_id",
                    crudkit.models.CrudKitPositiveIntegerField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("dry_run", models.BooleanField(default=False, editable=False)),
                (
                    "trigger_info",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                ("change_set", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("output", models.TextField(blank=True, default="", editable=False)),
                (
                    "preview",
                    models.JSONField(
                        blank=True,
                        default=list,
                        editable=False,
                        help_text="The proposals the run made, or would have made.",
                    ),
                ),
                ("error", models.TextField(blank=True, default="", editable=False)),
                (
                    "started_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="crudkit_assistant.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_merged_set",
                        to="crudkit_assistant.agentrun",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
