# Generated by Django 6.1.1 on 2026-09-19 21:02

import crudkit.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="currency",
            field=crudkit.fields.CurrencyField(max_length=3),
        ),
    ]
