# Generated by Django 5.1.15 on 2026-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0002_customer_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="watchers",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="testapp.customer"
            ),
        ),
    ]
