# Generated by Django 5.1.15 on 2026-10-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_ticket_watchers"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
